queues:
  - name: input-topic
    value: "localhost.kafka.input"
    type: kafka
    schema: example.data_models.InputMessage
  - name: queue_1
    value: long_name_1
    type: rsmq
    schema: dict
  - name: queue_2
    value: my_long_table_name
    type: postgres
    schema: volley.data_models.ComponentMessage
    producer: example.plugins.my_plugin.MyPGProducer
    consumer: example.plugins.my_plugin.MyPGConsumer
  - name: output-topic
    value: "localhost.kafka.output"
    type: kafka
    schema: example.data_models.OutputMessage
  - name: dead-letter-queue
    value: "localhost.kafka.dlq"
    type: kafka
    schema: volley.data_models.ComponentMessage
