queues:
  - name: input-queue
    value: "{{ env }}.kafka.input"
    type: kafka
    schema: example.data_models.InputMessage
  - name: comp_1
    value: comp1
    type: rsmq
    schema: example.data_models.Comp1Message
  - name: test_queue_plugin
    value: q42
    type: postgres
    schema: volley.data_models.ComponentMessage
    producer: example.plugins.my_plugin.MyPGProducer
    consumer: example.plugins.my_plugin.MyPGConsumer
  - name: output-queue
    value: "{{ env }}.kafka.output"
    type: kafka
    schema: example.data_models.OutputMessage
  - name: dead-letter-queue
    value: "{{ env }}.kafka.dlq"
    type: kafka
    schema: volley.data_models.ComponentMessage
