queues:
  - name: input-topic
    value: "localhost.kafka.input"
    type: kafka
    schema: example.data_models.InputMessage
  - name: redis_queue
    value: long_name_1
    type: rsmq
    schema: volley.data_models.ComponentMessage
  - name: postgres_queue
    value: my_long_table_name
    type: postgres
    schema: volley.data_models.ComponentMessage
    serializer: None
    producer: example.plugins.my_plugin.MyPGProducer
    consumer: example.plugins.my_plugin.MyPGConsumer
  - name: output-topic
    value: "localhost.kafka.output"
    type: kafka
    schema: example.data_models.OutputMessage
    config:
      group.id: localhost.example.consumer
      bootstrap.servers: kafka:29092
  - name: dead-letter-queue
    value: "localhost.kafka.dlq"
    type: kafka
    schema: volley.data_models.ComponentMessage
