kind: pipeline
name: test

trigger:
  event:
    - push
    - pull_request
    - tag
  branch:
    - main

steps:
  - name: unit-test
    image: python:3.9.4
    commands:
    - pip install poetry==1.1.10
    - poetry install
    - make test.unit
    environment:
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD

  - name: unit-test-python38
    image: python:3.8.0
    commands:
      - pip install poetry==1.1.10
      - poetry install
      - make test.unit
    environment:
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD

  - name: lints
    image: python:3.9.4
    commands:
      - pip install poetry==1.1.10
      - poetry install
      - make lints
    environment:
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD

  - name: integration-test
    image: python:3.9.4
    environment:
      APP_ENV: localhost
      KAFKA_BROKERS: kafka:9092
      GITHUB_PAT:
        from_secret: GITHUB_PAT
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
      - pip install poetry==1.1.10
      - poetry install
      - poetry run pytest tests/integration/integration_test.py

  - name: publish-release
    image: python:3.9.4
    environment:
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
      - pip install poetry==1.1.10
      - test "v$(poetry version --short)" "=" "$DRONE_TAG"
      - poetry publish --repository=shipt --build
    when:
      branch:
        - main
      event:
        - tag
    depends_on:
      - "integration-test"
      - "lints"
      - "unit-test"