kind: pipeline
name: unit-tests
type: docker

trigger:
  event:
    - push
    - pull_request
    - tag

steps:
  - name: unit-test-3.11
    image: python:3.11
    commands:
    - apt-get update -y && apt-get install -y --no-install-recommends gcc git libssl-dev g++ make
    - cd /tmp && git clone https://github.com/edenhill/librdkafka.git && cd librdkafka && ./configure --prefix=/usr && make && make install
    - cd /drone/src
    - curl -sSL https://install.python-poetry.org | POETRY_HOME=/ POETRY_VERSION=1.2.2 python3 -
    - poetry install -E all
    - poetry run pytest --ignore=tests/integration_tests

  - name: code-analysis
    image: plugins/sonarqube-drone-plugin
    environment:
      SONAR_HOST:
        from_secret: SONAR_HOST
      SONAR_TOKEN:
        from_secret: SONAR_TOKEN
    depends_on:
      - unit-test-3.11

  - name: unit-test-3.10
    image: python:3.10
    commands:
    - curl -sSL https://install.python-poetry.org | POETRY_HOME=/ POETRY_VERSION=1.2.2 python3 -
    - poetry install -E all
    - poetry run pytest --ignore=tests/integration_tests

  - name: unit-test-3.9
    image: python:3.9
    commands:
    - curl -sSL https://install.python-poetry.org | POETRY_HOME=/ POETRY_VERSION=1.2.2 python3 -
    - poetry install -E all
    - poetry run pytest --ignore=tests/integration_tests

  - name: unit-test-3.8
    image: python:3.8
    commands:
    - curl -sSL https://install.python-poetry.org | POETRY_HOME=/ POETRY_VERSION=1.2.2 python3 -
    - poetry install -E all
    - poetry run pytest --ignore=tests/integration_tests

---
kind: pipeline
type: docker
name: lints

workspace:
  path: /drone/src

trigger:
  event:
    - push
    - pull_request
    - tag

steps:
  - name: lints
    image: python:3.9.8
    commands:
      - curl -sSL https://install.python-poetry.org | POETRY_HOME=/ POETRY_VERSION=1.2.2 python3 -
      - poetry install -E all
      - make lints

---
kind: pipeline
type: docker
name: int-tests

workspace:
  path: /drone/src

trigger:
  event:
    - push
    - pull_request
    - tag
  branch:
    - main

steps:
  - name: test-integration
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
    - apk add make
    - sed -i -e '/volumes:/,+1d' docker-compose.yml
    - make test.integration

  - name: cleanup-test-integration
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - docker-compose logs
      - docker-compose down --remove-orphans
    depends_on:
      - test-integration
    when:
      status:
      - failure
      - success

---
kind: pipeline
type: docker
name: release

workspace:
  path: /drone/src

trigger:
  event:
    - tag
  branch:
    - main

depends_on:
  - unit-tests
  - int-tests
  - lints

steps:
  - name: publish-release
    image: python:3.9.4
    environment:
      POETRY_HTTP_BASIC_PYPI_USERNAME:
        from_secret: PYPI_ORG_USERNAME
      POETRY_HTTP_BASIC_PYPI_PASSWORD:
        from_secret: PYPI_ORG_PASSWORD
    commands:
      - curl -sSL https://install.python-poetry.org | POETRY_HOME=/ POETRY_VERSION=1.2.2 python3 -
      - test "v$(poetry version --short)" "=" "$DRONE_TAG"
        # publish to the public PyPI registry
      - poetry publish --build

---
kind: pipeline
type: docker
name: publish-docs

workspace:
  path: /drone/src

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: publish-docs
    image: python:3.10.2
    commands:
      - git diff $DRONE_COMMIT_BEFORE..$DRONE_COMMIT_AFTER --name-only | grep docs/ && export DOC_CHANGE=1 || export DOC_CHANGE=0;
      - if [ $DOC_CHANGE ] ; then make publish.docs; else echo "No doc change"; fi