kind: pipeline
name: test

trigger:
  event:
    - push
    - pull_request
    - tag

steps:
  - name: unit-tests
    image: python:3.9.4
    environment:
      SHIPT_PYPI_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      SHIPT_PYPI_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
      - pip3 install poetry==1.1.10
      - make test.unit
    environment:
      APP_ENV: 'localhost'

  - name: lints-quality
    image: python:3.9.4
    environment:
      SHIPT_PYPI_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      SHIPT_PYPI_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
      - pip3 install poetry==1.1.10
      - make lints.strict

  - name: docker-prep
    image: harbor.shipttech.com/plugins/dockerspec
    pull: always

  - name: docker-build-and-push
    image: plugins/docker
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      SHIPT_PYPI_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      SHIPT_PYPI_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    settings:
      build_args_from_env:
        - GITHUB_TOKEN
      registry: harbor.shipttech.com
      env_file: "docker_args"
    depends_on:
      - unit-tests
      - lints-quality
