kind: pipeline
name: test

trigger:
  event:
    - push
    - pull_request
    - tag
  branch:
    - main

steps:
  - name: unit-tests
    image: python:3.9.4
    environment:
      APP_ENV: 'localhost'
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
      - pip3 install poetry==1.1.11
      - poetry install
      - make test.unit

  - name: lints-quality
    image: python:3.9.4
    environment:
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
      - pip3 install poetry==1.1.11
      - poetry install
      - make lints

  - name: integration-test
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    environment:
      APP_ENV: localhost
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
    - apk add make
    - make test.integration

  - name: docker-prep
    image: harbor.shipttech.com/plugins/dockerspec
    pull: always

  - name: docker-build-and-push
    image: plugins/docker
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      SHIPT_PYPI_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      SHIPT_PYPI_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    settings:
      target: prod
      build_args_from_env:
        - GITHUB_TOKEN
        - SHIPT_PYPI_USERNAME
        - SHIPT_PYPI_PASSWORD
      registry: harbor.shipttech.com
      env_file: "docker_args"
    depends_on:
      - unit-tests
      - integration-test
