kind: pipeline
name: test

trigger:
  event:
    - push
    - pull_request
    - tag

steps:
  - name: unit-tests
    image: python:3.9.4
    environment:
      APP_ENV: 'localhost'
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
      - pip3 install poetry==1.1.11
      - poetry install
      - make test.unit

  - name: lints-quality
    image: python:3.9.4
    environment:
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
      - pip3 install poetry==1.1.11
      - poetry install
      - make lints

  - name: integration-test
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    environment:
      APP_ENV: localhost
      POETRY_HTTP_BASIC_SHIPT_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      POETRY_HTTP_BASIC_SHIPT_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    commands:
    - docker-compose -f test-compose.yml up --build -d
    - sleep 10
    - docker-compose exec -f test-compose.yml -T features pytest tests/integration_tests/test_integration.py
    - docker-compose down

  - name: docker-prep
    image: harbor.shipttech.com/plugins/dockerspec
    pull: always

  - name: docker-build-and-push
    image: plugins/docker
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
      SHIPT_PYPI_USERNAME:
        from_secret: SHIPT_PYPI_USERNAME
      SHIPT_PYPI_PASSWORD:
        from_secret: SHIPT_PYPI_PASSWORD
    settings:
      build_args_from_env:
        - GITHUB_TOKEN
        - SHIPT_PYPI_USERNAME
        - SHIPT_PYPI_PASSWORD
      registry: harbor.shipttech.com
      env_file: "docker_args"
    depends_on:
      - unit-tests
      - integration-test

services:
  - name: redis
    image: redis:6.2.6
    ports:
      - 6379

  - name: postgres
    image: postgres:12.3
    ports:
      - 5432
    environment:
        POSTGRES_PASSWORD: password
  
  - name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  - name: kafka
    image: bitnami/kafka:2.6.0
    ports:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: CLIENT://:9092
      KAFKA_ADVERTISED_LISTENERS: CLIENT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT