version: '3'
services:
    unit-tests:
        container_name: worker-unittests
        build:
            context: .
            dockerfile: tests/Dockerfile
        # depends_on:
        #     - redis
        environment:
            - APP_ENV=development
            - DEFAULT_MODEL_PATH=./trained_model/lin_reg_california_housing_model.joblib
    
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 30s
            retries: 50