version: '3'
services:
    # unit-tests:
    #     container_name: worker-unittests
    #     build:
    #         context: .
    #         dockerfile: tests/Dockerfile
    #         args:
    #             SHIPT_PYPI_USERNAME: ${POETRY_HTTP_BASIC_SHIPT_USERNAME}
    #             SHIPT_PYPI_PASSWORD: ${POETRY_HTTP_BASIC_SHIPT_PASSWORD}
    #     environment:
    #         - APP_ENV=localhost

    dummy_events:
        container_name: dummy_events
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - OUTPUT_QUEUE=input-topic
            - KAFKA_BROKERS=kafka:29092
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SHIPT_PYPI_USERNAME: ${POETRY_HTTP_BASIC_SHIPT_USERNAME}
                SHIPT_PYPI_PASSWORD: ${POETRY_HTTP_BASIC_SHIPT_PASSWORD}
        volumes:
            - ./:/app/
        depends_on:
            - redis
            - kafka
        command: python main.py dummy_events
    features:
        container_name: features
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - INPUT_QUEUE=input-topic
            - OUTPUT_QUEUE=triage
            - KAFKA_BROKERS=kafka:29092
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SHIPT_PYPI_USERNAME: ${POETRY_HTTP_BASIC_SHIPT_USERNAME}
                SHIPT_PYPI_PASSWORD: ${POETRY_HTTP_BASIC_SHIPT_PASSWORD}
        volumes:
            - ./:/app/
        # ports:
        #     - 5678:5678
        depends_on:
            - redis
            - kafka
        # command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client main.py features
        command: python main.py features
    triage:
        container_name: triage
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - INPUT_QUEUE=triage
            - OUTPUT_QUEUE=collector
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SHIPT_PYPI_USERNAME: ${POETRY_HTTP_BASIC_SHIPT_USERNAME}
                SHIPT_PYPI_PASSWORD: ${POETRY_HTTP_BASIC_SHIPT_PASSWORD}
        volumes:
            - ./:/app/
        depends_on:
            - redis
            - kafka
        # ports:
        #     - 5678:5678
        # command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client main.py triage
        command: python main.py triage
    collector:
        container_name: collector
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - INPUT_QUEUE=collector
            - OUTPUT_QUEUE=output-topic
            - KAFKA_BROKERS=kafka:29092
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SHIPT_PYPI_USERNAME: ${POETRY_HTTP_BASIC_SHIPT_USERNAME}
                SHIPT_PYPI_PASSWORD: ${POETRY_HTTP_BASIC_SHIPT_PASSWORD}
        volumes:
            - ./:/app/
        depends_on:
            - redis
            - kafka
        command: python main.py collector
    consumer:
        container_name: dummy_consumer
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - INPUT_QUEUE=output-topic
            - KAFKA_BROKERS=kafka:29092
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SHIPT_PYPI_USERNAME: ${POETRY_HTTP_BASIC_SHIPT_USERNAME}
                SHIPT_PYPI_PASSWORD: ${POETRY_HTTP_BASIC_SHIPT_PASSWORD}
        volumes:
            - ./:/app/
        depends_on:
            - redis
            - kafka
        command: python main.py dummy_consumer
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 30s
            retries: 50

    # Zookeeper required for Kafka broker at this time
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            KAFKA_JMX_PORT: 39999

    # Kakfa container required for unit testing
    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        restart: always
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
            - "7071:7071"
            - "49999:49999"
        # https://rmoff.net/2018/08/02/kafka-listeners-explained/
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_JMX_PORT: 49999