site_name: Data Science ML Experiment
site_author: Jason Eisele
theme:
  name: material
features:
  - navigation.expand
  # - navigation.indexes
nav:
  - Model Serving (API): ['overview.md', 'API.md', 'core.md', 'data_models.md', 'services.md']
  - Deploying: 'deploy.md'
repo_url: https://github.com/shipt/ml-experiment-template
