queues:
  - name: input-queue
    value: "{{ env }}.bus.ds-marketplace.v1.bundle_engine_input"
    type: kafka
  - name: triage
    value: triage
    type: rsmq
  - name: optimizer
    value: optimizer
    type: rsmq
  - name: fallback
    value: fallback
    type: rsmq
  # - name: shadow
  #   value: shadow
  #   type: rsmq
  - name: collector
    value: collector
    type: rsmq
  - name: output-queue
    value: "{{ env }}.bus.ds-marketplace.v1.bundle_engine_output"
    type: kafka
