{
 "title": "ml-bundle-engine-queues",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Component Avg Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(rate(process_time_seconds_sum{app=\"ml-bundle-engine\", process_name=\"component\"}[1m])) by (shipt_app_role_name) / sum(rate(process_time_seconds_count{app=\"ml-bundle-engine\", process_name=\"component\"}[1m])) by (shipt_app_role_name)",
       "legendFormat": "{{shipt_app_role_name}}"
      }
     ]
    },
    {
     "title": "Input Topic Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{topic=~\"prd.bus.ds-marketplace.v1.bundle_engine_input\"}) by (consumergroup, topic) ",
       "legendFormat": "topic: {{topic}} - group: {{consumergroup}}"
      }
     ]
    },
    {
     "title": "Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "bundle_engine_queue_length", "legendFormat": "{{queue_name}}" }
     ]
    },
    {
     "title": "Output Topic Production",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(delta(kafka_topic_partition_current_offset{topic=~\"prd.bus.ds-marketplace.v1.bundle_engine_output\"}[5m])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Feature Order Enrichment Summary",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(increase(order_counts_total{app=\"ml-bundle-engine\"}[1m])) by (shipt_app_role_name, status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  { "title": "Staging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Component Avg Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(process_time_seconds_sum{app=\"ml-bundle-engine\", process_name=\"component\"}[1m])) by (shipt_app_role_name) / sum(rate(process_time_seconds_count{app=\"ml-bundle-engine\", process_name=\"component\"}[1m])) by (shipt_app_role_name)",
     "legendFormat": "{{shipt_app_role_name}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(bundle_engine_queue_length) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Messages consumed per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(messages_consumed_count_total{app=\"ml-bundle-engine\"}[1m])) by (shipt_app_role_name)",
     "legendFormat": "{{shipt_app_role_name}}"
    }
   ]
  },
  {
   "title": "Messages produced per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(messages_produced_count_total{app=\"ml-bundle-engine\"}[1m])) by (shipt_app_role_name)",
     "legendFormat": "{{shipt_app_role_name}}"
    }
   ]
  },
  {
   "title": "Input Kafka Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"stg.bus.ds-marketplace.v1.bundle_engine_input\", consumergroup=\"staging_features\"})"
    }
   ]
  },
  {
   "title": "Input vs Output Kafka Message",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=~\"stg.bus.ds-marketplace.v1.bundle_engine_input\"}[10m]))",
     "legendFormat": "input-topic"
    },
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=~\"stg.bus.ds-marketplace.v1.bundle_engine_output\"}[10m]))",
     "legendFormat": "output-topic"
    }
   ]
  },
  {
   "title": "Feature Order Enrichment Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(order_counts_total{app=\"ml-bundle-engine\"}[1m])) by (shipt_app_role_name, status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Database Operation Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(postgres_process_time_seconds_sum[1m])) by (operation) / sum(increase(postgres_process_time_seconds_count[1m])) by (operation)",
     "legendFormat": "pg-{{operation}}"
    },
    {
     "expr": "sum(increase(redis_process_time_seconds_sum[1m])) by (operation) / sum(increase(redis_process_time_seconds_count[1m])) by (operation)",
     "legendFormat": "rsmq={{operation}}"
    }
   ]
  }
 ]
}