site_name: Volley
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: light mode

nav:
  - Volley: 'index.md'
  - Getting Started: 'example.md'
  - Configuration:
    - Queues: 'queue_config.md'
    - Profiles: 'profiles.md'
    - Application: 'engine.md'
    - Consumer & Producer: './connectors/connectors.md'
    - Serialization: './serializers/overview.md'
    - Model Handlers: './models/overview.md'
    - Dead Letter Queues: 'deadletterqueue.md'
  - Metrics: 'metrics.md'
  - Advanced Example: 'advanced_example.md'
  - Extending Volley:
    - Overview: 'extending.md'
    - Connectors:
      - Overview: 'connectors/overview.md'
      - ConfluentKafka: 'connectors/kafka.md'
      - RSMQ: 'connectors/rsmq.md' 
    - Serializers:
      - Overview: 'serializers/overview.md'
      - BaseSerialization: 'serializers/BaseSerialization.md'
      - JsonSerialization: 'serializers/JsonSerialization.md'
      - MsgPackSerialization: 'serializers/MsgPackSerialization.md'
      - OrJsonSerialization: 'serializers/OrJsonSerialization.md'
    - Model Handlers:
      - Overview: 'models/overview.md'
      - BaseModelHandler: 'models/BaseModelHandler.md'
      - PydanticModelHandler: 'models/PydanticModelHandler.md'
      - PydanticParserModelHandler: 'models/PydanticParserModelHandler.md'
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings
