name: integration tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.5.1"]
        os: [ubuntu]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip3 install poetry==${{ matrix.poetry-version }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - run: make setup.project
      - run: make test.integration
